'use client';

import { useState } from 'react';
import { useSubmitStep9 } from '@/hooks/useWorkflow';
import { CurriculumWorkflow, GlossaryTerm } from '@/types/workflow';

interface Props {
  workflow: CurriculumWorkflow;
  onComplete: () => void;
  onRefresh: () => void;
}

export default function Step9View({ workflow, onComplete, onRefresh }: Props) {
  const submitStep9 = useSubmitStep9();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [justGenerated, setJustGenerated] = useState(false);

  const handleGenerate = async () => {
    try {
      await submitStep9.mutateAsync(workflow._id);
      await onRefresh();
      setJustGenerated(true);
      // Step 9 doesn't need approval - it's auto-generated
      // Note: onComplete is handled by the parent after user clicks "Complete & Review"
    } catch (err) {
      console.error('Failed to generate glossary:', err);
    }
  };

  const hasStep9Data = workflow.step9 && workflow.step9.terms?.length > 0;

  // Filter terms
  const filteredTerms =
    workflow.step9?.terms?.filter((term) => {
      const matchesSearch = searchTerm
        ? term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
          term.definition.toLowerCase().includes(searchTerm.toLowerCase())
        : true;
      const matchesCategory = selectedCategory ? term.category === selectedCategory : true;
      return matchesSearch && matchesCategory;
    }) || [];

  return (
    <div className="p-6">
      {!hasStep9Data ? (
        <div className="space-y-6">
          <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-lg p-4">
            <h3 className="text-emerald-400 font-medium mb-2">Auto-Generated Glossary</h3>
            <p className="text-sm text-slate-300">
              The glossary is automatically generated by extracting key terms from all curriculum
              content. It includes definitions, related terms, and cross-references. No SME review
              required - this is the final step!
            </p>
          </div>

          <div className="text-center py-8">
            <div className="w-20 h-20 mx-auto mb-4 rounded-full bg-gradient-to-br from-cyan-500/20 to-blue-500/20 flex items-center justify-center">
              <svg
                className="w-10 h-10 text-cyan-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
                />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">Final Step!</h3>
            <p className="text-slate-400 mb-6">
              Generate the glossary to complete your curriculum package
            </p>
          </div>

          <button
            onClick={handleGenerate}
            disabled={submitStep9.isPending}
            className="w-full py-4 bg-gradient-to-r from-emerald-500 to-green-600 hover:from-emerald-400 hover:to-green-500 text-white font-medium rounded-lg transition-all disabled:opacity-50"
          >
            {submitStep9.isPending ? (
              <span className="flex items-center justify-center gap-2">
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating Glossary...
              </span>
            ) : (
              '🎉 Generate Glossary & Complete Workflow'
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Completion Banner */}
          <div className="bg-gradient-to-r from-emerald-500/20 to-green-500/20 border border-emerald-500/30 rounded-lg p-6 text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-emerald-500/20 flex items-center justify-center">
              <svg
                className="w-8 h-8 text-emerald-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <h3 className="text-xl font-bold text-emerald-400 mb-2">
              {justGenerated ? '🎉 Glossary Generated!' : 'Workflow Complete! 🎉'}
            </h3>
            <p className="text-slate-300 mb-4">
              {justGenerated
                ? 'Your glossary has been generated. Click "Complete & Review" in the header to finalize your curriculum.'
                : 'Your curriculum has been generated successfully. You can now export or publish.'}
            </p>
            {justGenerated && (
              <p className="text-cyan-400 text-sm animate-pulse">
                ↑ Click "Complete & Review" button above to finalize
              </p>
            )}
          </div>

          {/* Summary */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700 text-center">
              <p className="text-2xl font-bold text-white">{workflow.step9?.totalTerms || 0}</p>
              <p className="text-xs text-slate-500">Total Terms</p>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700 text-center">
              <p className="text-2xl font-bold text-cyan-400">
                {workflow.step9?.categories?.length || 0}
              </p>
              <p className="text-xs text-slate-500">Categories</p>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700 text-center">
              <p className="text-sm text-slate-400">
                {workflow.step9?.generatedAt
                  ? new Date(workflow.step9.generatedAt).toLocaleDateString()
                  : '-'}
              </p>
              <p className="text-xs text-slate-500">Generated</p>
            </div>
          </div>

          {/* Search & Filter */}
          <div className="flex gap-4">
            <div className="flex-1">
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="Search terms..."
                className="w-full px-4 py-2 bg-slate-900/50 border border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500"
              />
            </div>
            <select
              value={selectedCategory || ''}
              onChange={(e) => setSelectedCategory(e.target.value || null)}
              className="px-4 py-2 bg-slate-900/50 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
            >
              <option value="">All Categories</option>
              {workflow.step9?.categories?.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
          </div>

          {/* Glossary Terms */}
          <div>
            <h3 className="text-lg font-semibold text-white mb-3">
              Glossary ({filteredTerms.length} terms)
            </h3>
            <div className="grid gap-3">
              {filteredTerms.map((term) => (
                <div
                  key={term.id}
                  className="bg-slate-900/50 rounded-lg p-4 border border-slate-700"
                >
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <h4 className="text-white font-medium">{term.term}</h4>
                    {term.category && (
                      <span className="text-xs px-2 py-1 rounded bg-slate-700 text-slate-400">
                        {term.category}
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-slate-300 mb-2">{term.definition}</p>
                  {term.relatedTerms && term.relatedTerms.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      <span className="text-xs text-slate-500">Related:</span>
                      {term.relatedTerms.map((related, i) => (
                        <span key={i} className="text-xs text-cyan-400">
                          {related}
                          {i < term.relatedTerms!.length - 1 ? ',' : ''}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Regenerate button */}
          <div className="flex items-center justify-center pt-4 border-t border-slate-700">
            <button
              onClick={handleGenerate}
              disabled={submitStep9.isPending}
              className="px-4 py-2 text-slate-400 hover:text-white"
            >
              Regenerate Glossary
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
